### PR TITLE
add opengrid network to public networks

### PR DESCRIPTION
**Pull request by shubham3121**
## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by madhavajay** [comment]
@shubham3121 I can connect to opengrid but not to the other machine with IP 20.245.137.204, I also can't ping it.

**Comment by shubham3121** [comment]
@madhavajay that machine is still down, I can remove it from the list, although it won't appear in the sy.networks.

**Comment by madhavajay** [comment]
@shubham3121 I can merge if its supposed to be on there. Are we supposed to be adding a machine thats not online to sy.networks? Will we be bringing it back up later with the same version for some reason?

**Comment by shubham3121** [comment]
Let me remove it, I had kept it just to keep track of the VM. We won't be bringing it back with the same version.

**Pull request merged**
